"""add inspections advances incidents and trip paused

Revision ID: 1bf4d7a637ed
Revises: 4169f99a1921
Create Date: 2026-07-13 19:36:14.077693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf4d7a637ed'
down_revision: Union[str, None] = '4169f99a1921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='advancestatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decider_name', sa.String(length=120), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deducted_trip_id', sa.Integer(), nullable=True),
    sa.Column('deducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deducted_trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advances_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_advances_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advances_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_advances_trip_id'), ['trip_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('BREAKDOWN', 'ACCIDENT', 'OTHER', name='incidentkind'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('gps', sa.String(length=60), nullable=True),
    sa.Column('photo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='incidentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolver_name', sa.String(length=120), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_incidents_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_trip_id'), ['trip_id'], unique=False)

    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('defect_note', sa.Text(), nullable=False),
    sa.Column('defect_photo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='inspectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=120), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_trip_id'), ['trip_id'], unique=False)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paused', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('paused')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_trip_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_status'))
        batch_op.drop_index(batch_op.f('ix_inspections_driver_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_trip_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_driver_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_code'))

    op.drop_table('incidents')
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advances_trip_id'))
        batch_op.drop_index(batch_op.f('ix_advances_status'))
        batch_op.drop_index(batch_op.f('ix_advances_driver_id'))
        batch_op.drop_index(batch_op.f('ix_advances_code'))

    op.drop_table('advances')
    # ### end Alembic commands ###
