"""photo fields to string paths + receipt photo

Revision ID: 21e2370960e8
Revises: 1bf4d7a637ed
Create Date: 2026-07-13 22:50:58.849024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e2370960e8'
down_revision: Union[str, None] = '1bf4d7a637ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('tarp',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.alter_column('defect_photo',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

    # แปลงค่าธง boolean เดิม → path string: 1/True = "attached" (เคยมีรูปแบบ flag), 0 = NULL
    for table, cols in [("drops", ["photo", "tarp"]), ("incidents", ["photo"]), ("inspections", ["defect_photo"])]:
        for c in cols:
            op.execute(f"UPDATE {table} SET {c} = CASE WHEN {c} IN (1, '1', 'true') THEN 'attached' ELSE NULL END")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.alter_column('defect_photo',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.alter_column('tarp',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
