"""add dispatch difficulty rating penalty

Revision ID: 4169f99a1921
Revises: ca8037b066e2
Create Date: 2026-07-12 21:17:33.172443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4169f99a1921'
down_revision: Union[str, None] = 'ca8037b066e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('creator_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalties_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalties_trip_id'), ['trip_id'], unique=False)

    # server_default เพื่อเติมค่าให้แถวเดิมที่มีอยู่แล้ว (กัน NOT NULL fail)
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='tripdifficulty'), nullable=False, server_default='MEDIUM'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalties_trip_id'))
        batch_op.drop_index(batch_op.f('ix_penalties_driver_id'))

    op.drop_table('penalties')
    # ### end Alembic commands ###
