"""เพิ่ม drops.loaded_photo — รูปของที่ขนขึ้นรถแล้ว

คนขับถ่ายในหน้ายืนยันตอนกด "ขนของขึ้นเสร็จ" (🟠 → 🟢) เก็บเป็น URL ไฟล์จริง
(/uploads/loaded-*.jpg) ลงขาปัจจุบันของทริป

nullable=True เพราะขาเก่าที่วิ่งไปก่อนมีด่านนี้ไม่มีรูป — ปล่อยเป็น NULL
(= ไม่มีหลักฐาน ตามความจริง) ไม่ backfill ค่าปลอมย้อนหลัง

Revision ID: 949330a52469
Revises: b4f5e115f276
Create Date: 2026-07-19 23:04:55.188176
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949330a52469'
down_revision: Union[str, None] = 'b4f5e115f276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loaded_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.drop_column('loaded_photo')

    # ### end Alembic commands ###
