"""initial schema

Revision ID: ca8037b066e2
Revises: 
Create Date: 2026-07-12 18:11:23.777560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8037b066e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('who', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_at'), ['at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('DRIVER', 'SUPERVISOR', 'ADMIN', 'SUPER_ADMIN', name='role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notif', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_emp_id'), ['emp_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=50), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('WHITE', 'ORANGE', 'GREEN', name='tripstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_loading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tarpaulin_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tarp_escalated', sa.Boolean(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('penalty', sa.Float(), nullable=False),
    sa.Column('penalty_reason', sa.Text(), nullable=False),
    sa.Column('frozen_fuel', sa.Float(), nullable=True),
    sa.Column('frozen_toll', sa.Float(), nullable=True),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('override', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_trips_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_status'), ['status'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('std_km_l', sa.Float(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_plate'), ['plate'], unique=True)

    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(length=120), nullable=False),
    sa.Column('field_key', sa.String(length=40), nullable=False),
    sa.Column('field_label', sa.String(length=120), nullable=False),
    sa.Column('old_val', sa.Float(), nullable=False),
    sa.Column('new_val', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='correctionstatus'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrections_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_corrections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrections_trip_id'), ['trip_id'], unique=False)

    op.create_table('drops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowance', sa.Float(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.Boolean(), nullable=False),
    sa.Column('tarp', sa.Boolean(), nullable=False),
    sa.Column('gps', sa.String(length=60), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'seq', name='uq_drop_trip_seq')
    )
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drops_trip_id'), ['trip_id'], unique=False)

    op.create_table('gps_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.Enum('LOADED', 'DELIVERED', name='gpsevent'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gps_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gps_logs_trip_id'), ['trip_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('FUEL', 'TOLL', name='receiptkind'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drop_id', 'kind', name='uq_receipt_drop_kind')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_drop_id'), ['drop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_drop_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('gps_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gps_logs_trip_id'))

    op.drop_table('gps_logs')
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drops_trip_id'))

    op.drop_table('drops')
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrections_trip_id'))
        batch_op.drop_index(batch_op.f('ix_corrections_status'))
        batch_op.drop_index(batch_op.f('ix_corrections_code'))

    op.drop_table('corrections')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_plate'))

    op.drop_table('vehicles')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_status'))
        batch_op.drop_index(batch_op.f('ix_trips_driver_id'))
        batch_op.drop_index(batch_op.f('ix_trips_code'))

    op.drop_table('trips')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_emp_id'))

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_at'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
